### ISSUE TITLE
Now what?

### ISSUE THREAD

**Issue by TriangularDev** [Ceald1/Token-API#1]
I can get it running on ubuntu server just fine, but what do I even do after installing and running it?

**Comment by Ceald1** [comment]
I'm working on a GUI wallet that will also act as a node and server as a way to make wallet keys. It will be a while until I make a fully functional GUI application for wallets.

**Comment by TriangularDev** [comment]
K

**Comment by Ceald1** [comment]
I have the API running on heroku, https://token-node0.herokuapp.com/    https://token-node1.herokuapp.com/ 
you should be able to add the 2 nodes in add_nodes, and don't add the https:// when adding nodes

**Comment by TriangularDev** [comment]
The web UI looks really cool!
